module.exports = {
    SUCCESS : 0,
    ERROR : 500,
    LOGIN_EXCEPTION : 501,
    FIRESTORE_UPDATE_FAIL : 502,
    FIRESTORE_GET_FAIL : 503,
    UPLOAD_FAIL : 510,
    GET_UPLOADED_FILE_FAIL : 511,

    UNAUTHORIZED : 300,
    USER_NOT_FOUND : 301,
    USER_EXISTS : 302,

    RESTAURANT_NOT_FOUND : 310,
    RESTAURANT_CREATE_FAIL : 311,
    CREATE_FOOD_FAIL : 312,
    FOOD_NOT_FOUND : 313,

    CREATE_COMMENT_FAIL: 320,
    
    WRONG_FORMAT : 400,

    GOOGLE_LOGIN_FAIL : 600,

    FACEBOOK_LOGIN_FAIL : 650,


};